name: Bug report
description: Report errors or unexpected behaviour
title: "[Bug]: "
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?
      description: Please update Spotify, Spicetify, and the extensions from this repo or use the auto-update method to resolve common issues.
      options:
        - label: I have confirmed that I am using the latest versions.
          required: true
  - type: checkboxes
    attributes:
      label: 🔍 Have you checked for an existing issue?
      description: Ensure your issue is not already reported by checking the <a href="https://github.com/daksh2k/Spicetify-stuff/issues?q=is%3Aissue">existing issues</a>. Check both open and closed issues, as your problem may have been resolved already.
      options:
        - label: I have checked existing issues, both open and closed.
          required: true
  - type: checkboxes
    attributes:
      label: 🔍 Have you reviewed pinned issues?
      options:
        - label: I have reviewed the pinned issues.
          required: true

  - type: dropdown
    attributes:
      label: Select the relevant extension for this bug report.
      description: Choose the extension related to the issue from the dropdown.
      options:
          - Save Playlists
          - Full Screen Mode
          - Auto Skip
          - Play Next
          - Volume Percentage
          - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: ℹ System Information
      description: Provide details of the system running Spicetify. You can copy this info from Spotify's About section.
      placeholder: |
        Example:
        Spotify for macOS (Intel) 1.2.18.999.g9b38fc27
        Spicetify v2.22.2
        Extensions: keyboardShortcutMy.js, fullScreen.js, hidePodcasts.js, autoSkipWrapper.js, playNextWrapper.js, volumePercentageWrapper.js, savePlaylistsWrapper.js, css-editor.js, queuePanel.js, CoverAmbience.js, QueueTime.js, adblock.js
        Custom apps: marketplace, lyrics-plus
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 Bug Description
      description: Describe the steps to reproduce the error, what happens, and what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 Screenshots
      description: Attach any screenshots of the issue, if applicable.
    validations:
      required: false
